name: W 4

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > file1.txt
      - shell: bash
        run: |
          expr 3 + 10 > file2.txt
      - shell: bash
        run: |
          expr 3 + 20 > file3.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: n1
          path: |
            file[12].txt
            file3.txt
