name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > file1.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: n1
          path: file1.txt
